### ISSUE TITLE
Do not support AArch64 machine

### ISSUE THREAD

**Issue by mimirang** [indutny/elfy#1]
If a binary has Machine: AArch64 on ELF header, elf parser returns machine :"undefined" .  

```
readelf -h testBin
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           AArch64

```
Need to add the machine definition to constants.machine : 

```
constants.machine = { 
+  95: 'num',
+  183: 'AArch64'
}

```
Please refer to : https://en.wikipedia.org/wiki/Executable_and_Linkable_Format

**Comment by indutny** [comment]
Thank you for the report! Would you care submitting a PR for this?

**Comment by mimirang** [comment]
Please review https://github.com/indutny/elfy/pull/2 :)

**Comment by mimirang** [comment]
https://github.com/indutny/elfy/pull/2 is merged. 
I'm closing this ticket.
